# -*- coding: utf-8 -*-
"""fight_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhIM5a58OigiTBE5xxh_gjscXbQr8VV-
"""

!pip install torch torchvision torchaudio open_clip_torch opencv-python

import torch
import open_clip
import cv2
import numpy as np
from PIL import Image

def analyze_image(image_path):
    image = Image.open(image_path).convert("RGB")
    image = preprocess(image).unsqueeze(0)

    texts = ["A fight scene", "A peaceful scene"]
    text_tokens = tokenizer(texts)

    with torch.no_grad():
        image_features = model.encode_image(image)
        text_features = model.encode_text(text_tokens)

        similarity = (image_features @ text_features.T).softmax(dim=-1)
        fight_prob = similarity[0][0].item()
        peaceful_prob = similarity[0][1].item()

    result = "Fight Detected!" if fight_prob > peaceful_prob else "No Fight Detected."
    print(f" Fight Probability: {fight_prob:.2f}, Peaceful Probability: {peaceful_prob:.2f}")
    print(f" Result: {result}")

from google.colab import files
uploaded = files.upload()

import os
file_path = '/content/drive/My Drive/colab data/fight_detection/fight.jpeg'  # Adjust this path if needed
if os.path.exists(file_path):
    print(" File found!")
else:
    print(" File not found. Check the path.")

analyze_image("fight.jpeg")